### ISSUE TITLE
Input prefix of the model mengzi-t5-base

### ISSUE THREAD

**Issue by KarenMars** [Langboat/Mengzi#46]
Hi,

I have a question regarding the input of the model mengzi-t5-base. In the original paper of T5, it mentions that "we need to add the task-specific prefix to the original input sequence before feeding it to the model". I wonder that if I want to perform text summarize task with mengzi-t5-base or other downstream tasks, do I need to add some prefix, and what the prefix should be. Thank you very much for your help, looking forward to your reply.

**Comment by Ag2S1** [comment]
mengzi-t5-base was trained following google's t5 v1.1. It was trained on general corpus only without mixing downstream tasks.
You can directly finetune it on your summarisation dataset.

**Comment by KarenMars** [comment]
Thank you very much, your answer is very helpful.
